### PR TITLE
C++11 Iterator replacement for Vectored Exceptions Interface

### PR DESCRIPTION
**Pull request by Maktm**
These 3 commits update the old implementation of accessing the Windows vectored exceptions linked list located in ntdll. Read/write is now possible using the iterators.

Since this is C++11 compliant (thanks @RaptorFactor) you can use it like any other iterator.

```
VectoredHandlerList list{Process{::GetCurrentProcessId()}};
for(auto iter = list.begin(); iter != list.end(); ++iter)
{
  std::cout << DecodePointer(iter->Handler) << std::endl;
}
```

Note that you have to use DecodePointer since it provides a direct interface to the Windows data structures. Also, because of this you can write to the data structures as such:

```
VectoredHandlerList list{Process{::GetCurrentProcessId()}};
for(auto iter = list.begin(); iter != list.end(); ++iter)
{
  iter->Handler = nullptr;
}
```

Note that the example above nulls out every vectored exception handler in the current process.

### CODE REVIEW

**Comment by Maktm** [comment]
You can remove the mutex feature of the iterator in order to separately implement an insert/delete method that uses the locks provided by Windows if you feel it's better to do it that way.

**Comment by RaptorFactor** [comment]
I'm finally back... I'm the worst.

This looks great although I'm confused about one thing. What do you mean when you refer to the "mutex feature of the iterator", I don't see any mutex? I see the SrwLock in the vectored handler list but as you say that's not used right now.

As for using the SrwLock that will require some thought as to whether that could potentially cause deadlocks. I think it should be okay unless you're hooking an API that's actively modifying the list and has an exclusive hold on it, but there's probably a way to check that and bail... (I'm not positive but iirc a srwlock is just a bitmask and you can peek inside to check stuff...)

Thanks for contributing this!

**Comment by Maktm** [comment]
Not really sure what I meant either at the moment. I guess I was trying to suggest adding a lock similar to that of Windows but yeah, I didn't implement any lock features. Also, the fact that the user has to use DecodePointer kind of sucks because it's hard to remember to do this. A class that overloads some operators and decodes, encodes on-the-fly is creatable but it would have to be defined in winternl.hpp because the VEH data structures would have to use it (and they're defined there). But since winternl.hpp is for Windows data structures I just left it out.

Yeah, no problem.

**Comment by RaptorFactor** [comment]
Merging as-is for now. I'll continue to think about the locking aspect (and wrapper).

**Pull request merged**
